image: python:3.7.3

pipelines:
  default:
    - step:
        name: Install requirements, run tests and generate coverage report
        caches:
          - pip
        script:
          - cd project
          - pip install -r requirements.txt
          - chmod +x test.sh
          - ./test.sh
