image: python:3.7.3

pipelines:
  default:
    - step:
        name: Install requirements, run tests and generate coverage report
        caches:
          - pip
        script:
          - cd project
          - pip install -r requirements.txt
          - chmod u+x generate_config.sh
          - ./generate_config.sh
          - nose2 -s tests
          - coverage run -m nose2 -s tests
          - coverage report -m
