runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --log-level=debug main:app

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

runtime_config:
  python_version: 3

# Enable a TCP domain socket
beta_settings:
  cloud_sql_instances: plexiform-plane-295614:us-central1:test-db

env_variables:
  DB_USER: postgres
  DB_PASS: dfNht3Dd2FLmp6yw
  DB_NAME: postgres
  DB_HOST: 34.71.176.179
  CONNECTION_NAME: plexiform-plane-295614:us-central1:test-db